version: '3.8'
services:
  companytech-app: 
    image: sungaibudiwebdev/dazytech:latest
    container_name: dazytech-app
    restart: unless-stopped
    expose:
      - "80" 
    networks:
      - web-network

networks:
  web-network:
    external: true