/* ============================================================
   VIETNAM NORTH TRIP by Rere — 13–21 Feb 2027
   Data hardcode (transkrip dari sheet planning).
   Ubah isi file ini saja kalau ada perubahan jadwal.
   ============================================================ */

export const TRIP = {
    title: "Vietnam North Trip",
    owner: "by Rere",
    dateLabel: "13–21 Februari 2027",
    route: ["Jakarta", "Hanoi", "Sapa", "Ha Long Bay", "Jakarta"],
    routeLabel: "Hanoi → Sapa 3D2N → Ha Long Bay → Jakarta",
    startISO: "2027-02-13",
    endISO: "2027-02-21",
    // Landing di Noi Bai
    countdownISO: "2027-02-13T18:15:00+07:00",
    assumptions:
        "Asumsi & info terkini (per Sep 2026): Xanh SM / Green SM Car default di Hanoi (Grab backup); di Sapa pakai mobil hotel / taksi lokal. WNI bebas visa maks 14 hari sejak 15 Jul 2026 — trip 9 hari aman, paspor berlaku ≥6 bulan. Jam Fansipan & operator final dicek H-30 / H-14 dan pagi hari-H.",
    ruleOfThumb:
        "FIXED dijaga → FLEX boleh digeser → OPTIONAL langsung di-drop kalau waktu / cuaca / tenaga tidak mendukung.",
};

export const SIFAT = {
    FIXED: {
        label: "WAJIB",
        emoji: "🔒",
        bg: "#FFE7E2",
        fg: "#C0362C",
        border: "#FFC2B8",
        desc: "Tidak boleh digeser",
    },
    FLEX: {
        label: "FLEKSIBEL",
        emoji: "🔁",
        bg: "#FFF3D6",
        fg: "#96660A",
        border: "#FFE0A3",
        desc: "Boleh digeser kalau meleset",
    },
    OPTIONAL: {
        label: "OPSIONAL",
        emoji: "💤",
        bg: "#EEF1F6",
        fg: "#5F6C82",
        border: "#DCE3EC",
        desc: "Boleh langsung di-drop",
    },
};

export const DAYS = [
    {
        id: 1,
        date: "2027-02-13",
        dayLabel: "Sab, 13 Feb",
        title: "Hanoi — Arrival",
        emoji: "🛬",
        city: "Hanoi",
        accent: "#FF5A3C",
        tag: "Landing malam + dinner pertama",
        photo: "day1",
        imgCaption: "Welcome to Hanoi — malam pertama di Old Quarter",
        items: [
            {
                time: "18:15",
                act: "Landing di Noi Bai (HAN)",
                sifat: "FIXED",
            },
            {
                time: "18:15–19:30",
                act: "Imigrasi, baggage, toilet, SIM / cash seperlunya",
                trans: "Di dalam bandara",
                sifat: "FLEX",
            },
            {
                time: "19:30–20:30",
                act: "Noi Bai → hotel Old Quarter",
                trans: "Green SM Car / Grab Car / transfer hotel",
                sifat: "FIXED",
                note: "Budget 45–60 menit. Simpan alamat hotel dalam bahasa Vietnam.",
            },
            {
                time: "20:30–20:45",
                act: "Check-in dan taruh koper",
                trans: "Jalan kaki di area hotel",
                sifat: "FIXED",
            },
            {
                time: "20:45–21:45",
                act: "Dinner pertama",
                trans: "Jalan kaki",
                food: "Pho 10 Ly Quoc Su / Street Food",
                foodStar: true,
                sifat: "FLEX",
                note: "Pho 10 bukan kewajiban Day 1. Kalau antre >20–30 menit atau sudah terlalu lapar, makan dekat hotel; pindahkan Pho 10 ke Day 4 brunch/lunch.",
            },
            {
                time: "21:45++",
                act: "Hotel / jalan singkat kalau masih kuat",
                trans: "Jalan kaki",
                sifat: "OPTIONAL",
            },
        ],
    },
    {
        id: 2,
        date: "2027-02-14",
        dayLabel: "Min, 14 Feb",
        title: "Hanoi + Fitting",
        emoji: "👗",
        city: "Hanoi",
        accent: "#F5A524",
        tag: "Anchor: fitting baju prewed 14:00",
        photo: "day2",
        imgCaption: "Train Street pas kereta lewat — agenda sore",
        items: [
            {
                time: "08:00–09:00",
                act: "Bangun dan breakfast",
                trans: "Jalan kaki",
                food: "Dekat hotel",
                sifat: "FLEX",
            },
            {
                time: "09:15–10:15",
                act: "Tran Quoc Pagoda",
                trans: "Green SM Car",
                sifat: "FLEX",
                note: "Kalau hujan deras, ganti dengan aktivitas indoor / cafe dan pertahankan fitting.",
            },
            {
                time: "10:15–11:30",
                act: "St. Joseph Cathedral + Hoan Kiem / egg coffee",
                trans: "Green SM lalu jalan kaki",
                food: "Cafe Giang (viral egg coffee)",
                foodStar: true,
                sifat: "FLEX",
                note: "Cafe Giang boleh dipindah ke Day 4; tidak perlu mengejar semua spot.",
            },
            {
                time: "11:30–12:45",
                act: "Lunch",
                trans: "Green SM Car",
                food: "Bun Cha Huong Lien",
                foodStar: true,
                sifat: "FLEX",
                note: "Kalau perjalanan meleset, pilih lunch dekat area fitting supaya tidak terlambat.",
            },
            {
                time: "12:45–13:40",
                act: "Ke hotel / area fitting + freshen up + buffer",
                trans: "Green SM Car",
                sifat: "FIXED",
                note: "Target sudah berada dekat lokasi fitting paling lambat 13:40.",
            },
            {
                time: "14:00–16:30",
                act: "Fitting baju prewed",
                trans: "Sesuai arahan vendor",
                sifat: "FIXED",
                note: "Konfirmasi lokasi dan durasi H-1; ini tidak boleh dikorbankan untuk city tour.",
            },
            {
                time: "16:30–18:30",
                act: "Train Street Hanoi",
                trans: "Green SM Car",
                sifat: "FIXED",
                note: "Sengaja kosong untuk persiapan prewed besok.",
            },
            {
                time: "18:30–21:00",
                act: "Dinner ringan / massage?",
                trans: "Green SM / jalan kaki",
                food: "Dekat hotel / cafe Train Street",
                sifat: "OPTIONAL",
                note: "Target street food: Banh Mi, cha and pork, famous roti King Roti.",
            },
        ],
    },
    {
        id: 3,
        date: "2027-02-15",
        dayLabel: "Sen, 15 Feb",
        title: "Prewedding",
        emoji: "💍",
        city: "Hanoi",
        accent: "#FF6FA5",
        tag: "Anchor: photoshoot seharian — hari inti trip",
        photo: "day3",
        imgCaption: "Referensi konsep: clean studio (Amory Studio)",
        items: [
            {
                time: "Pagi–sore",
                act: "Prewedding photoshoot",
                trans: "Transport vendor / Green SM sesuai lokasi",
                food: "Makan mengikuti jadwal vendor",
                sifat: "FIXED",
                note: "Call time dan lokasi diisi setelah vendor konfirmasi. Sisakan snack, air minum, dan outer.",
            },
            {
                time: "Setelah selesai",
                act: "Dinner dekat hotel / delivery",
                trans: "Jalan kaki / delivery",
                food: "Tidak ada restoran wajib",
                sifat: "FIXED",
                note: "Tidak ada aktivitas malam. Langsung mandi, backup foto kalau perlu, lalu tidur.",
            },
        ],
    },
    {
        id: 4,
        date: "2027-02-16",
        dayLabel: "Sel, 16 Feb",
        title: "Recovery + Sleeper",
        emoji: "🛌",
        city: "Hanoi → Sapa",
        accent: "#7C6BF2",
        tag: "Santai seharian, malam naik sleeper bus",
        photo: "day4",
        imgCaption: "Kabin VIP sleeper bus Hanoi → Sapa",
        items: [
            {
                time: "09:00–12:00",
                act: "Bangun santai, brunch, mandi, packing",
                trans: "Jalan kaki",
                food: "Pho 10 (fallback slot)",
                foodStar: true,
                sifat: "FLEX",
                note: "Ini slot terbaik untuk Pho 10 kalau terlewat Day 1. Jangan korbankan waktu packing.",
            },
            {
                time: "12:00",
                act: "Check-out dan titip koper",
                trans: "Hotel storage",
                sifat: "FIXED",
                note: "Konfirmasi hotel bersedia menyimpan koper sampai malam.",
            },
            {
                time: "12:15–15:00",
                act: "Lunch santai + massage / spa",
                trans: "Green SM / jalan kaki",
                food: "Fleksibel",
                sifat: "FLEX",
                note: "Kalau prewed dipindah karena hujan, seluruh blok ini yang pertama dihapus.",
            },
            {
                time: "15:00–17:00",
                act: "Cafe / Old Quarter super santai",
                trans: "Jalan kaki",
                food: "Cafe Giang (fallback slot)",
                sifat: "OPTIONAL",
                note: "Bisa diatur ke Temple of Literature kalau mau.",
            },
            {
                time: "17:00–20:00",
                act: "Ambil barang, early dinner, buffer",
                trans: "Jalan kaki",
                food: "Street Food",
                sifat: "FIXED",
                note: "Siapkan pakaian ganti, tisu basah, obat pribadi, dan barang tidur bus di tas kecil.",
            },
            {
                time: "20:00–21:15",
                act: "Ambil koper + ke bus pickup / office",
                trans: "Green SM Car",
                sifat: "FIXED",
                note: "Berangkat lebih awal karena titik pickup bisa bukan depan hotel.",
            },
            {
                time: "~22:30–23:30",
                act: "Sleeper bus Hanoi → Sapa",
                trans: "VIP sleeper cabin",
                sifat: "FIXED",
                note: "Target operator yang tiba 05:00–06:00 atau mengizinkan tetap tidur sampai sekitar 06:00. Jam final belum di-lock.",
            },
        ],
    },
    {
        id: 5,
        date: "2027-02-17",
        dayLabel: "Rab, 17 Feb",
        title: "Sapa + Cat Cat",
        emoji: "🏔️",
        city: "Sapa",
        accent: "#10B981",
        tag: "Anchor: Cat Cat Village",
        photo: "day5",
        imgCaption: "Cat Cat Village",
        items: [
            {
                time: "~05:00–07:00",
                act: "Tiba Sapa, freshen up, titip koper",
                trans: "Taksi lokal / hotel pickup",
                sifat: "FIXED",
                note: "Jangan mengandalkan Green SM / Grab di Sapa; minta hotel bantu transport.",
            },
            {
                time: "07:00–10:00",
                act: "Breakfast + early check-in, mandi & istirahat singkat",
                trans: "Jalan kaki / taksi lokal",
                food: "Hotel breakfast / resto lokal",
                sifat: "FLEX",
                note: "Recover dari sleeper bus supaya siang kuat ke Cat Cat.",
            },
            {
                time: "10:00–13:00",
                act: "Sapa town / Stone Church / Sun Plaza + lunch",
                trans: "Jalan kaki",
                food: "Lunch lokal sekitar Sun Plaza",
                sifat: "FLEX",
                note: "Gabung town walk + lunch supaya blok siang bebas untuk Cat Cat.",
            },
            {
                time: "13:00–16:30",
                act: "Cat Cat Village",
                trans: "Taksi lokal ke entrance; lanjut jalan kaki",
                food: "Snack ringan / kopi di dalam",
                sifat: "FLEX",
                note: "Blok siang–sore untuk Cat Cat. Kalau hujan / lelah boleh dipangkas.",
            },
            {
                time: "16:30–18:00",
                act: "Balik hotel, freshen up / cafe view",
                trans: "Taksi lokal / jalan kaki",
                sifat: "OPTIONAL",
                note: "Boleh langsung istirahat singkat sebelum dinner.",
            },
            {
                time: "19:00–20:30",
                act: "Dinner khas Sapa",
                trans: "Jalan kaki / taksi lokal",
                food: "Salmon hotpot — A Phu / Cá Hồi Vua (King Salmon)",
                foodStar: true,
                sifat: "FLEX",
                note: "Kalau antre panjang, pilih hotpot dekat hotel. Restoran bukan anchor.",
            },
        ],
    },
    {
        id: 6,
        date: "2027-02-18",
        dayLabel: "Kam, 18 Feb",
        title: "Fansipan Main Day",
        emoji: "🚡",
        city: "Sapa",
        accent: "#0EA5E9",
        tag: "Anchor: Fansipan — go/no-go jam 07:40",
        photo: "day6",
        imgCaption: "Puncak Fansipan di atas lautan awan",
        items: [
            {
                time: "06:30–07:40",
                act: "Bangun dan breakfast",
                trans: "Jalan kaki",
                food: "Hotel breakfast",
                sifat: "FIXED",
                note: "Berpakaian berlapis; siapkan jas hujan tipis dan sarung tangan.",
            },
            {
                time: "07:40–08:00",
                act: "Cek cuaca, visibility, angin, dan operasional",
                trans: "Cek kanal resmi / tanya hotel",
                sifat: "FIXED",
                note: "Keputusan go/no-go Fansipan dibuat sebelum berangkat.",
            },
            {
                time: "08:00–12:15",
                act: "Sun Plaza → funicular / cable car → kompleks puncak",
                trans: "Monorail + cable car",
                sifat: "FLEX",
                note: "Budget 3–4 jam door-to-door. Kalau whiteout / angin kuat / operasional berhenti, swap ke Day 7 pagi.",
            },
            {
                time: "12:30–15:00",
                act: "Lunch + hotel rest",
                trans: "Jalan kaki",
                food: "Fleksibel",
                sifat: "FIXED",
                note: "Jangan langsung menumpuk aktivitas setelah turun.",
            },
            {
                time: "15:00–17:30",
                act: "Cafe / Muong Hoa view / town",
                trans: "Taksi / jalan kaki",
                food: "Cafe view",
                sifat: "OPTIONAL",
                note: "Pilih satu saja sesuai cuaca dan tenaga.",
            },
            {
                time: "18:30++",
                act: "Dinner dan istirahat",
                trans: "Jalan kaki",
                food: "Fleksibel",
                sifat: "FLEX",
                note: "Packing sebagian untuk check-out besok.",
            },
        ],
    },
    {
        id: 7,
        date: "2027-02-19",
        dayLabel: "Jum, 19 Feb",
        title: "Sapa → Hanoi (Early)",
        emoji: "🚐",
        city: "Sapa → Hanoi",
        accent: "#84CC16",
        tag: "Van paling pagi + blok oleh-oleh",
        photo: "day7",
        imgCaption: "Lotte Mart Hanoi — blok oleh-oleh",
        items: [
            {
                time: "06:45–07:45",
                act: "Breakfast + check-out",
                trans: "Jalan kaki",
                food: "Hotel breakfast",
                sifat: "FIXED",
                note: "Selesaikan check-out pagi; kejar van paling pagi.",
            },
            {
                time: "07:45–08:30",
                act: "Ambil koper & menuju pickup",
                trans: "Taksi lokal / jalan kaki",
                sifat: "FIXED",
                note: "Standby 15–30 menit sebelum van. Ambil jadwal keberangkatan paling pagi.",
            },
            {
                time: "~08:30–14:30",
                act: "Van / bus Sapa → Hanoi (jadwal paling pagi)",
                trans: "Day van / bus",
                food: "Snack ringan dibawa sendiri",
                sifat: "FIXED",
                note: "Planning 5,5–6 jam. Target tiba Hanoi awal sore.",
            },
            {
                time: "14:30–15:30",
                act: "Check-in hotel Hanoi + taruh koper",
                trans: "Green SM / jalan kaki",
                sifat: "FIXED",
                note: "Langsung taruh koper biar ringan ke Lotte.",
            },
            {
                time: "15:30–18:30",
                act: "Beli oleh-oleh ke Lotte (Lotte Center / Mall)",
                trans: "Green SM Car",
                food: "Snack / food court Lotte",
                sifat: "FLEX",
                note: "Blok oleh-oleh. Selesaikan sebelum terlalu lelah.",
            },
            {
                time: "18:30++",
                act: "Dinner / massage",
                trans: "Green SM / jalan kaki",
                food: "Dekat hotel / delivery",
                sifat: "FLEX",
                note: "Lanjut packing.",
            },
        ],
    },
    {
        id: 8,
        date: "2027-02-20",
        dayLabel: "Sab, 20 Feb",
        title: "Ha Long Bay",
        emoji: "⛵",
        city: "Ha Long Bay",
        accent: "#2563EB",
        tag: "Anchor: cruise Sung Sot / Luon / Titop",
        photo: "day8",
        imgCaption: "Cruise di Ha Long Bay",
        items: [
            {
                time: "06:30–07:15",
                act: "Bangun, breakfast, sudah siap",
                trans: "Jalan kaki",
                food: "Hotel breakfast",
                sifat: "FIXED",
                note: "Final packing sebaiknya 90% selesai sejak malam Day 7.",
            },
            {
                time: "07:30–11:30",
                act: "Pickup / meeting point → Ha Long",
                trans: "Transfer tour",
                sifat: "FIXED",
                note: "Pickup mungkin bukan di depan lobby; konfirmasi titik dan waktu H-1.",
            },
            {
                time: "11:30–17:30",
                act: "Boarding, cruise, lunch, Sung Sot / Luon / Titop, sunset",
                trans: "Kapal sharing",
                food: "Lunch biasanya sudah termasuk",
                sifat: "FIXED",
                note: "Pilih itinerary Route 2-style. Jangan tambah aktivitas malam setelah cruise.",
            },
            {
                time: "18:00–20:30/21:30",
                act: "Ha Long → Hanoi",
                trans: "Transfer tour",
                food: "Snack di kendaraan",
                sifat: "FIXED",
                note: "Return bisa molor. Pastikan operator memberi estimasi drop-off yang realistis.",
            },
            {
                time: "~21:00–22:15",
                act: "Dinner sangat simpel, final packing, tidur",
                trans: "Delivery / jalan kaki",
                food: "Dekat hotel / delivery",
                sifat: "FIXED",
                note: "Karena flight pagi, tidak ada restoran wajib. Pasang alarm ganda dan siapkan dokumen.",
            },
        ],
    },
    {
        id: 9,
        date: "2027-02-21",
        dayLabel: "Min, 21 Feb",
        title: "Pulang",
        emoji: "✈️",
        city: "Hanoi → Jakarta",
        accent: "#E11D48",
        tag: "Flight 08:40 — bangun 04:15",
        photo: "day9",
        imgCaption: "Noi Bai Terminal 2 — pintu pulang",
        items: [
            {
                time: "04:15–04:45",
                act: "Bangun dan check-out",
                food: "Breakfast box kalau tersedia",
                sifat: "FIXED",
                note: "Semua koper dan pakaian sudah siap malam sebelumnya.",
            },
            {
                time: "04:45–05:45",
                act: "Old Quarter → Noi Bai T2",
                trans: "Green SM Car terjadwal; Grab / hotel car backup",
                sifat: "FIXED",
                note: "Untuk penerbangan, hotel / private car jadi Plan C kalau assignment app tidak meyakinkan.",
            },
            {
                time: "05:45–07:45",
                act: "Check-in, bag drop, imigrasi, breakfast",
                trans: "Di bandara",
                food: "Bandara",
                sifat: "FIXED",
                note: "Target tiba sekitar 3 jam sebelum penerbangan internasional.",
            },
            {
                time: "08:40",
                act: "Flight pulang",
                trans: "Pesawat",
                sifat: "FIXED",
                note: "Waktu penerbangan ini menggantikan rencana lama 'flight sore/malam'.",
            },
        ],
    },
];

export const CONTINGENCY = [
    {
        id: "prewed-hujan",
        emoji: "🌧️",
        title: "Prewed hujan",
        trigger: "Forecast jelek H-3 / H-1 atau hujan di Day 3",
        respons:
            "Koordinasikan vendor: kerjakan indoor / studio / cafe dulu, manfaatkan window kering untuk outdoor.",
        alternatif:
            "Kalau full-day harus pindah: gunakan Day 4 pagi–sore, hapus recovery activities dan ambil sleeper paling malam.",
        drop: "Massage, cafe, Pho 10 Day 4",
        batas: "Final dengan vendor H-1",
        catatan:
            "Kalau shoot Day 4 selesai lewat ~17:00, jangan memaksa sleeper; ubah bus dan terima bahwa Day 5 Sapa ikut bergeser / lebih pendek.",
    },
    {
        id: "halong-cancel",
        emoji: "⛵",
        title: "Ha Long gagal jalan",
        trigger: "Operator cancel H-1 / pelabuhan tutup / cuaca buruk",
        respons:
            "Kalau diketahui H-1 dan kondisi darat aman: ambil Ninh Binh day trip (Trang An + satu stop darat saja).",
        alternatif: "Kalau batal mendadak pagi hari: Hanoi indoor + spa / cafe + early rest.",
        drop: "Semua aktivitas tambahan malam",
        batas: "H-1 pukul 18:00; recheck pagi",
        catatan:
            "Jangan pindah ke Lan Ha bila pembatalan disebabkan penutupan pelabuhan / cuaca regional. Refund & cancellation policy harus jelas saat booking.",
    },
    {
        id: "fansipan-kabut",
        emoji: "🌫️",
        title: "Fansipan tertutup kabut / angin",
        trigger: "Visibility buruk atau cable car terganggu",
        respons: "Nikmati town / cafe / view ringan. Cat Cat sudah di Day 5, jadi tidak diulang.",
        alternatif: "Swap ke Day 7 pagi kalau masih memungkinkan.",
        drop: "Cafe / view tambahan Day 6",
        batas: "Day 6 pukul 07:40",
        catatan:
            "Fansipan > Cat Cat. Jangan mengejar checklist ketika cuaca tidak memberi view. Cat Cat kini anchor Day 5.",
    },
    {
        id: "resto-ramai",
        emoji: "🍜",
        title: "Restoran ramai",
        trigger: "Antrean >20–30 menit atau sudah terlalu lapar",
        respons: "Pilih restoran setipe yang paling dekat.",
        alternatif: "Pindahkan target kuliner ke slot Hanoi / Sapa berikutnya.",
        drop: "Nama restoran — bukan waktu istirahat",
        batas: "Saat tiba di lokasi",
        catatan:
            "Pho 10 paling mudah dipindah ke Day 4 brunch/lunch; Pizza 4P's jangan dibuat anchor setelah perjalanan Sapa.",
    },
    {
        id: "greensm",
        emoji: "🚗",
        title: "Green SM sulit dapat",
        trigger: "ETA lama, cancel berulang, atau lokasi pickup membingungkan",
        respons: "Bandingkan dengan Grab Car.",
        alternatif: "Minta hotel panggil taxi / private car, terutama untuk ke bandara.",
        drop: "Tidak ada",
        batas: "Setelah 1–2 cancel",
        catatan: "Green SM default hanya di Hanoi. Di Sapa gunakan hotel-arranged car / taksi lokal.",
    },
    {
        id: "koper-sapa",
        emoji: "🧳",
        title: "Koper saat ke Sapa",
        trigger: "Kembali ke Hanoi dan hotel bersedia storage",
        respons: "Titip koper besar di hotel Hanoi; bawa tas untuk 2 malam saja ke Sapa.",
        alternatif: "Kalau ganti hotel / tidak boleh titip, bawa kabin seminimal mungkin.",
        drop: "Barang non-esensial",
        batas: "Konfirmasi sebelum Day 4",
        catatan:
            "Ini membuat sleeper bus jauh lebih nyaman. Dokumen, obat, dan valuables selalu dibawa bersama.",
    },
    {
        id: "halong-telat",
        emoji: "🌙",
        title: "Ha Long pulang terlambat",
        trigger: "ETA hotel lewat 21:30",
        respons: "Delivery / dinner sangat simpel, final check dokumen, tidur.",
        alternatif: "Minta breakfast box untuk dibawa ke bandara.",
        drop: "Semua aktivitas malam",
        batas: "Saat bus mendekati Hanoi",
        catatan:
            "Packing 90% sudah selesai sejak malam Day 7; alarm ganda dan airport ride sudah disiapkan.",
    },
    {
        id: "jam-operator",
        emoji: "⏱️",
        title: "Jam operator berubah",
        trigger: "Jadwal 2027 berbeda dari estimasi",
        respons: "Pertahankan urutan dan buffer, geser blok yang fleksibel.",
        alternatif: "Drop OPTIONAL dulu sebelum mengurangi buffer FIXED.",
        drop: "Cafe tambahan, Train Street, Cat Cat (kalau cuaca buruk)",
        batas: "H-30 lalu H-14 / H-1",
        catatan: "Jam di sheet ini adalah planning window, bukan janji operator.",
    },
];

export const FOOD_SECTIONS = [
    {
        id: "hanoi",
        label: "Hanoi",
        emoji: "🏙️",
        subtitle: "Food & street food",
        accent: "#FF5A3C",
        items: [
            {
                id: "h1",
                name: "Pho 10 (Ly Quoc Su)",
                cat: "Pho",
                emoji: "🍜",
                note: "Michelin 2023 & 2024",
                photo: "pho10",
                real: true,
                must: true,
                day: 1,
            },
            {
                id: "h13",
                name: "Bun Cha Huong Lien",
                cat: "Bun Cha",
                emoji: "🍢",
                note: "Target lunch Day 2 — bun cha legendaris",
                photo: "buncha",
                day: 2,
            },
            {
                id: "h14",
                name: "King Roti",
                cat: "Roti",
                emoji: "🍞",
                note: "Viral street treat, ±VND 25k — target malam Day 2",
                photo: "kingroti",
                real: true,
                day: 2,
            },
            { id: "h2", name: "Don Duck", cat: "Bebek", emoji: "🦆", note: "Ramai, Michelin — hindari jam makan siang", photo: "duck" },
            { id: "h3", name: "Loc Tai House", cat: "Dessert", emoji: "🍮", note: "Tempat dessert", photo: "dessert" },
            { id: "h4", name: "Pho Thin", cat: "Pho", emoji: "🍜", note: "Best pho versi TikTok", photo: "pho" },
            { id: "h5", name: "Bancong Café", cat: "Café", emoji: "☕", note: "Café viral (view-oriented)", photo: "coffee" },
            { id: "h6", name: "Café Giang", cat: "Café", emoji: "🥚", note: "Spot legendaris — egg coffee", photo: "eggcoffee", day: 2 },
            { id: "h7", name: "Banh Mi 25", cat: "Banh Mi", emoji: "🥖", note: "Populer, sandwich khas Vietnam", photo: "banhmi" },
            { id: "h8", name: "Bun Cha Ta", cat: "Bun Cha", emoji: "🍢", note: "Michelin Bun Cha", photo: "buncha" },
            { id: "h9", name: "Pizza 4P's", cat: "Pizza", emoji: "🍕", note: "Half & half pizza", photo: "pizza" },
            { id: "h10", name: "Chou Steak", cat: "Steak", emoji: "🥩", photo: "steak" },
            { id: "h11", name: "Hao Hao Coffee", cat: "Café", emoji: "🚂", note: "Spot Train Street", photo: "haohao", real: true },
            { id: "h12", name: "Pho Ga Nguyet", cat: "Pho", emoji: "🍲", note: "Cocok buat sarapan (dry noodle)", photo: "pho" },
        ],
    },
    {
        id: "sapa",
        label: "Sapa",
        emoji: "🏔️",
        subtitle: "Tempat makan",
        accent: "#10B981",
        items: [
            {
                id: "s1",
                name: "Viettrekking Coffee",
                cat: "Café",
                emoji: "☕",
                note: "Train view Sapa",
                photo: "viettrekking",
                real: true,
            },
            { id: "s2", name: "Saling Sapa", cat: "Restoran", emoji: "🍽️" },
            { id: "s3", name: "Anise Sapa", cat: "Bun Cha", emoji: "🍢", note: "Bun cha", price: "VND 165k", photo: "buncha" },
            { id: "s4", name: "Viet Deli", cat: "Steak", emoji: "🥩", note: "Horse tenderloin", price: "VND 325k", photo: "steak" },
            { id: "s5", name: "Hotpot Center", cat: "Hotpot", emoji: "🍲", note: "Salmon hotpot", price: "VND 800k", photo: "hotpot" },
            {
                id: "s6",
                name: "A Phu",
                cat: "Hotpot",
                emoji: "🐟",
                note: "Salmon hotpot — pilihan dinner Day 5",
                photo: "hotpot",
                day: 5,
            },
            {
                id: "s7",
                name: "Cá Hồi Vua (King Salmon)",
                cat: "Hotpot",
                emoji: "🍲",
                note: "Salmon hotpot — pilihan dinner Day 5",
                photo: "hotpot",
                day: 5,
            },
        ],
    },
    {
        id: "places",
        label: "Main",
        emoji: "🎡",
        subtitle: "Things to do di Sapa",
        accent: "#0EA5E9",
        items: [
            { id: "p1", name: "Alpine Coaster (Cat Cat)", cat: "Wahana", emoji: "🎢", photo: "alpinecoaster", real: true },
            { id: "p2", name: "Muong Pet Farm Sapa", cat: "Farm", emoji: "🦙", note: "Bisa ketemu alpaca", photo: "alpaca" },
            { id: "p3", name: "Bridge to the Clouds", cat: "Spot foto", emoji: "🌉", photo: "cloudbridge", real: true },
            { id: "p4", name: "Rainbow Slide", cat: "Wahana", emoji: "🌈", photo: "rainbow", real: true },
            { id: "p5", name: "Mario Kart Ride", cat: "Wahana", emoji: "🏎️", note: "O Quy Ho Fairy Valley", photo: "mariokart", real: true },
        ],
    },
    {
        id: "souvenir",
        label: "Oleh-oleh",
        emoji: "🛍️",
        subtitle: "Belanja & buah tangan",
        accent: "#F5A524",
        items: [
            { id: "o1", name: "Souvenir Store Ha Phuong", cat: "Toko", emoji: "🏪", note: "Tempat belanja oleh-oleh", photo: "market" },
            { id: "o2", name: "Vifon – Phở Bò", cat: "Instant Pho", emoji: "🍜", note: "Instant rice noodle rasa beef", photo: "vifon", real: true },
            { id: "o3", name: "Coconut Coffee", cat: "Kopi", emoji: "🥥", note: "Merk REXSUN / HATA", photo: "coffee" },
            { id: "o4", name: "Legendary Chocolate", cat: "Cokelat", emoji: "🍫", photo: "chocolate", real: true },
            { id: "o5", name: "Chabong", cat: "Abon (pork floss)", emoji: "🥓", note: "Banh gao an cha bong — ±VND 54k", photo: "chabong", real: true },
            { id: "o7", name: "C'est Bon", cat: "Keju", emoji: "🧀", note: "Snack keju — wajib beli", photo: "cestbon", real: true, must: true },
        ],
    },
];

export const BUDGET = {
    kurs: 0.68, // 1 VND = Rp 0,68
    plan: [
        { id: "b1", item: "Pesawat", desc: "PP Jakarta – Hanoi", rp: 8100000, vnd: 11911765, emoji: "✈️" },
        { id: "b2", item: "Hotel Hanoi", desc: "5 malam @ Rp350k", rp: 1750000, vnd: 2573529, emoji: "🏨" },
        { id: "b3", item: "Hotel Hanoi (stay 2)", desc: "2 malam @ Rp350k", rp: 700000, vnd: 1029412, emoji: "🏨" },
        { id: "b4", item: "Halong Bay", desc: "2 pax @ Rp850k", rp: 1700000, vnd: 2500000, emoji: "⛵" },
        { id: "b5", item: "Bus Hanoi – Sapa (PP)", desc: "VND 730.000 × 2", rp: 1000000, vnd: 1470588, emoji: "🚌" },
        { id: "b6", item: "Telkomsel Roaming", desc: "Paket data", rp: 200000, vnd: 294118, emoji: "📶" },
        { id: "b7", item: "Fansipan", desc: "Monorail + cable car + peak train", rp: 1600000, vnd: 2352941, emoji: "🚡" },
        { id: "b8", item: "Cash pegangan", desc: "Jajan & lain-lain", rp: 6000000, vnd: 8823529, emoji: "💵" },
        { id: "b9", item: "Prewedding", desc: "Total paket (input VND)", rp: 16252000, vnd: 23900000, emoji: "📸" },
    ],
    planTotal: { rp: 37302000, vnd: 54855882 },
    actual: [
        {
            id: "r1",
            item: "Pesawat",
            desc: "Cicilan BliBli Paylater Rp2,7jt/bln mulai Sep 2026 (pesan 10 Agu 2026)",
            rp: null,
            vnd: null,
            emoji: "✈️",
            status: "Cicilan jalan",
        },
        {
            id: "r2",
            item: "Hotel Hanoi 13–16 Feb",
            desc: "Queen Café Hotel & Pub · cashback ~Rp200k after checkout — pay at hotel",
            rp: 1373328,
            vnd: 2019600,
            emoji: "🏨",
            status: "Booked",
        },
        {
            id: "r3",
            item: "Hotel Hanoi 19–21 Feb",
            desc: "Cashback ~$4.8 after checkout — pay at hotel",
            rp: 915552,
            vnd: 1346400,
            emoji: "🏨",
            status: "Booked",
        },
        {
            id: "r4",
            item: "Prewedding (DP)",
            desc: "DP; sisa dibayar saat acara",
            rp: 1360000,
            vnd: 2000000,
            emoji: "📸",
            status: "DP masuk",
        },
    ],
    actualTotal: { rp: 3648880, vnd: 5366000 },
    footnote:
        "Total realisasi belum menghitung pesawat karena dibayar lewat cicilan bulanan. Angka realisasi hotel = harga booking, dibayar saat check-out di hotel.",
};

export const PACKING = [
    { id: "k1", name: "Tongsis / Tripod (Bluetooth)", emoji: "🤳" },
    { id: "k2", name: "Sunscreen", emoji: "🧴" },
    { id: "k3", name: "Paspor", emoji: "🛂" },
    { id: "k4", name: "Travel Adapter Universal", emoji: "🔌" },
    { id: "k5", name: "Jaket / Sweater / Sarung tangan", emoji: "🧥" },
    { id: "k6", name: "Payung kecil", emoji: "☂️" },
    { id: "k7", name: "Download Gmaps offline Hanoi + Sapa", emoji: "🗺️" },
    { id: "k8", name: "Sling bag", emoji: "👜" },
    { id: "k9", name: "Powerbank", emoji: "🔋" },
];

export const TIPS = [
    { text: "Jangan lupa isi Vietnam Digital Arrival Card — 3 hari sebelum berangkat.", star: true },
    {
        text: "Sewa kostum di Sapa: masuk ke dalam, jangan di pintu masuk — lebih murah & banyak pilihan. Overprice VND 400k, harga wajar VND 200–250k.",
    },
    { text: "Ambil paket monorail + cable car + peak train VND 1.320k (Klook, kode: DETOURSITAKLOOK)." },
    { text: "Tempat belanja: Dong Xuan (baju), Dong Xuan Market (makanan)." },
    {
        text: "Tarik uang bisa di VP Bank.",
        sub: "Cabang VPBank Nguyễn Hữu Huân (Old Quarter) — Senin 08.00–12.00 & 13.00–17.00.",
        photo: "vpbank",
        photoRatio: "440/272",
    },
    { text: "Fansipan usahakan sampai pagi (10–11), karena tutup ~15.30." },
    { text: "Bawa sarapan & minuman sebelum ke pesawat." },
    { text: "VietJet antriannya panjang — datang jauh sebelum boarding." },
    { text: "Cek lagi apakah Fansipan sedang maintenance." },
    { text: "Kalau malas taksi, bisa naik bus 86 ke Old Quarter (murah)." },
];

/* Modus penipuan yang paling sering kena turis.
   Infografik sumber: @outsideinvietnam (ditampilkan lewat lightbox). */
export const SCAMS = [
    {
        id: "taxi",
        emoji: "🚕",
        title: "Taksi palsu / argo “rusak”",
        modus:
            "Sopir bilang argonya rusak lalu pasang tarif flat yang jauh lebih mahal. Ada juga taksi abal-abal yang meniru logo dan nomor telepon perusahaan resmi seperti Mai Linh atau Vinasun.",
        fix: "Pakai aplikasi: Grab, Xanh SM, atau Be — harga sudah fix dari awal. Kalau terpaksa naik taksi jalanan, pastikan argonya jalan sebelum berangkat.",
        photo: "scam-taxi",
    },
    {
        id: "money",
        emoji: "💵",
        title: "Uang ditukar saat bayar",
        modus:
            "Pecahan 500.000 dan 20.000 VND sama-sama biru dan mirip sekali. Penjual menukar uangmu diam-diam lalu bilang kamu cuma kasih yang kecil.",
        fix: "Pisahkan pecahan besar di slot dompet yang berbeda. Bayar pelan-pelan sambil menyebut nominalnya, dan jangan lepas pandangan dari uangnya.",
        photo: "scam-money",
    },
    {
        id: "photo",
        emoji: "📸",
        title: "Foto “gratis” pakai pikulan",
        modus:
            "Pedagang menawarkan kamu memegang pikulan buah atau caping untuk difoto, katanya gratis. Begitu dipegang, mereka memaksa bayar.",
        fix: "Tolak tegas tapi sopan: “Không, cảm ơn” (tidak, terima kasih), lalu jalan terus. Jangan pegang barang dagangan siapa pun.",
        photo: "scam-photo",
    },
    {
        id: "food",
        emoji: "🍩",
        title: "“Cobain dulu, gratis!”",
        modus:
            "Ditawari mencicipi donat, buah potong, atau kacang — katanya gratis. Setelah dicicipi, harganya ditagih berlipat-lipat dan susah ditawar. Di restoran, camilan yang tiba-tiba muncul di meja (kacang, tisu basah, acar) juga tetap masuk bill walau tidak dipesan.",
        fix: "Jangan terima apa pun yang disodorkan. Tanya harga dan pastikan angkanya dulu sebelum menyentuh atau makan. Camilan yang tidak dipesan, dorong balik sambil bilang tidak mau.",
    },
    {
        id: "shoe",
        emoji: "👟",
        title: "Semir sepatu dadakan",
        modus:
            "Tukang semir jalanan tiba-tiba menyemprot sepatumu atau bilang solnya lepas, langsung mengerjakan tanpa diminta, lalu menagih 300.000–500.000 VND.",
        fix: "Bilang “No!” dan mundur — jangan lepas sepatu. Kalau masih diikuti, masuk ke toko terdekat.",
        photo: "scam-shoe",
    },
    {
        id: "scooter",
        emoji: "🛵",
        title: "Sewa motor",
        modus:
            "Saat motor dikembalikan, pemilik menunjuk baret yang sebenarnya sudah ada sejak awal dan menuntut biaya perbaikan besar — kadang paspor ditahan sebagai jaminan.",
        fix: "Rekam video 360° kondisi motor sebelum jalan. Tinggalkan deposit uang, jangan pernah paspor.",
        photo: "scam-scooter",
    },
];

export const HERO_IMG = "/vietnam-2027/hero.jpg";

/* Foto milik sendiri — tidak perlu kredit. */
export const OWN_PHOTOS = [
    "day1", "day2", "day3", "day4", "day5", "day7", "day8", "day9",
    "pho10", "viettrekking", "vpbank", "haohao", "kingroti",
    "alpinecoaster", "cloudbridge", "mariokart", "rainbow",
    "cestbon", "chabong", "chocolate", "vifon",
];

/* Kredit foto Wikimedia Commons — wajib untuk lisensi CC BY / CC BY-SA. */
export const PHOTO_CREDITS = [
    { file: "Ha Long Bay (hero)", author: "lumoplank", license: "CC0", url: "https://commons.wikimedia.org/wiki/File:Ha_Long_Bay_-_Halong1407.jpg" },
    { file: "Fansipan (Day 6)", author: "Vivu Vietnam", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Fansipan_summit_spiritual_complex_bare_tree_sea_of_clouds_Sa_Pa_Vietnam.jpg" },
    { file: "Phở", author: "jwalsh", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Pho_dish.jpg" },
    { file: "Egg coffee", author: "David McKelvey", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Egg_Coffee_(6923068614).jpg" },
    { file: "Bánh mì", author: "Stu Spivack", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:B%C3%A1nh_m%C3%AC.jpg" },
    { file: "Bún chả", author: "Stuart Spivack", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:B%C3%BAn_ch%E1%BA%A3_Vietnamese_food.jpg" },
    { file: "Bebek", author: "JIP", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Roast_duck_at_restaurant_Kyl%C3%A4.jpg" },
    { file: "Chè (dessert)", author: "Zxcvasdfqwer888", license: "CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Ch%C3%A8_B%E1%BA%AFp.jpg" },
    { file: "Kopi phin", author: "Phương Huy", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:C%C3%A0_ph%C3%AA_v%C3%A0_tr%C3%A0_%C4%91%C3%A1_v%E1%BB%89a_h%C3%A8_%E1%BB%9F_Qu%E1%BA%ADn_3_ng%C3%A0y_05_th%C3%A1ng_3_n%C4%83m_2020_(3).jpg" },
    { file: "Pizza", author: "jeffreyw", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Pizza_Margherita_(14565452088).jpg" },
    { file: "Steak", author: "Ceeseven", license: "CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Beef_Steak_on_Sizzling_Plate.jpg" },
    { file: "Hotpot", author: "Green Mostaza", license: "CC BY 4.0", url: "https://commons.wikimedia.org/wiki/File:Hot_pot_(1),_AA_Yau_Tsim_Mong_2013.jpg" },
    { file: "Alpaca", author: "Christine Matthews", license: "CC BY-SA 2.0", url: "https://commons.wikimedia.org/wiki/File:Alpaca,_Mudchute_Farm,_London_E14_-_geograph.org.uk_-_4387847.jpg" },
    { file: "Chợ Đồng Xuân", author: "Juliana Ng", license: "CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Dong_Xuan_market.jpg" },
];

/* Sumber infografik scam. */
export const SCAM_CREDIT = {
    author: "@outsideinvietnam",
    url: "https://www.tiktok.com/@outsideinvietnam",
};
